apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-consumer
  namespace: p2-namespace
  labels:
    app: go-consumer
spec:
  selector:
    matchLabels:
      app: go-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: go-consumer
    spec:
      containers:
      - name: backend
        image: andrecorado/go_consumer:0.08
        resources:
          limits:
            memory: 128Mi
            cpu: 200m         
        
