FROM rust:latest as builder
WORKDIR /usr/src/app
COPY . .
RUN apt-get update && apt-get install -y libssl-dev cmake && \
    cargo build --release

FROM ubuntu:latest
RUN apt-get update && apt-get install -y libssl-dev
COPY --from=builder /usr/src/app/target/release/app-servidor /usr/local/bin/app-servidor
EXPOSE 8080
CMD ["app-servidor"]


# docker build -t andrecorado/app_server .
# docker run -p 8080:8080 andrecorado/app_server