apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-app
  namespace: p2-namespace
  labels:
    app: rust-app
spec:
  selector:
    matchLabels:
      app: rust-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rust-app
    spec:
      containers:
      - name: client
        image: andrecorado/rust_client:0.2
        ports:
        - containerPort: 8000        
      - name: server
        image: andrecorado/rust_server:0.03
        imagePullPolicy: Always
        ports:
        - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: rust-app
  namespace: p2-namespace
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: rust-app
  type: ClusterIP
