apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-p2
  namespace: p2-namespace
spec:
  rules:
    - http:
        paths:
          - path: /grpc
            pathType: Prefix
            backend:
              service:
                name: grpc-app
                port:
                  number: 3000
                   